Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  ControlPortAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  AssociateControlPort:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt ControlPortAddress.AllocationId
      NetworkInterfaceId: !Ref controlXface
Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  controlXface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref SubnetId
      Description: Interface for controlling traffic such as SSH
      GroupSet: 
      - !Ref SSHSecurityGroup
      SourceDestCheck: true
      Tags:
        -
          Key: Network
          Value: Control
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
        - all-traffic-allowed
      KeyName: !Ref KeyName
      NetworkInterfaces:
        -
          NetworkInterfaceId: !Ref controlXface
          DeviceIndex: 0
      Tags: 
        - 
          Key: "Name"
          Value: "Joseph-Demo"
      #ImageId: ami-6871a115 / RHEL
      ImageId: ami-afd15ed0 #/ Amazon Linux
      InstanceType: t2.micro
      UserData:
        "Fn::Base64":
          !Sub |
          #!/bin/bash
          sudo su -
          yum install -y mailx telnet mutt dovecot
          yum update -y
          setenforce 0
          systemctl stop firewalld
          useradd demo
          echo "demo:demo1" | chpasswd
          usermod -aG mail demo
          sed -i '$adisable_plaintext_auth = no' /etc/dovecot/conf.d/10-auth.conf
          sed -i '$amail_location = mbox:~/mail:INBOX=/var/mail/%u' /etc/dovecot/conf.d/10-mail.conf
          systemctl restart dovecot
          # Let postfix recieve all traffic, not only localhost
          postconf -e "inet_interfaces = all"
          postconf -e "mydestination = josephaws.one, email.josephaws.one, josephaws.com, email.josephaws.com, localhost"
          systemctl restart postfix
          # Prepare some data for imap/pop3 test
          for i in {1..5}
          do
              #echo "Welcome $i times"
              echo hello$i | mail -s "test$i" demo@localhost.
          done
