Resources:
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-6871a115
      InstanceType: t2.micro
      KeyName: devenv-key
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd php mysql php-mysql -y
            yum update -y
