AWSTemplateFormatVersion: 2010-09-09

Description: >
    AWS DefaultVPC+NLB+TargetGroup+ASG+LaunchConfig+Dovecot+Postfix+LinuxFileSystem PoC Demo.
Parameters:

  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S,M,L)

Mappings:

  RegionMap:
    us-east-1:
      "AMALINUX" : "ami-afd15ed0" # AMALINUX 2 MAY 2018 
    us-east-2:
      "AMALINUX" : "ami-71ca9114" # AMALINUX SEP 2016
    us-west-1:
      "AMALINUX" : "ami-de347abe" # AMALINUX SEP 2016
    us-west-2:
      "AMALINUX" : "ami-b04e92d0" # AMALINUX SEP 2016
    ca-central-1:
      "AMALINUX" : "ami-c59818a1" # AMALINUX 2 May 2018 
    eu-west-1:
      "AMALINUX" : "ami-d41d58a7" # AMALINUX SEP 2016
    eu-central-1:
      "AMALINUX" : "ami-0044b96f" # AMALINUX SEP 2016
    eu-west-2:
      "AMALINUX" : "ami-bfe0eadb" # AMALINUX SEP 2016 v01
    ap-southeast-1:
      "AMALINUX" : "ami-7243e611" # AMALINUX SEP 2016
    ap-southeast-2:
      "AMALINUX" : "ami-55d4e436" # AMALINUX SEP 2016
    ap-northeast-2:
      "AMALINUX" : "ami-a04297ce" # AMALINUX SEP 2016
    ap-northeast-1:
      "AMALINUX" : "ami-1a15c77b" # AMALINUX SEP 2016
    ap-south-1:
      "AMALINUX" : "ami-cacbbea5" # AMALINUX SEP 2016
    sa-east-1:
      "AMALINUX" : "ami-b777e4db" # AMALINUX SEP 2016
  
  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
      "DB" : "db.t2.small"
    LARGE:
      "EC2" : "t2.medium"
      "DB" : "db.t2.medium"
  
Resources:

  Ec2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: EC2 Security Group
	  
  ingress1:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !GetAtt Ec2SecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: 110
      ToPort: 110
      CidrIp: 0.0.0.0/0
	  
  ingress2:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !GetAtt Ec2SecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: 143
      ToPort: 143
      CidrIp: 0.0.0.0/0
	  
  ingress3:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !GetAtt Ec2SecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0
	  
  ingress4:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !GetAtt Ec2SecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: 25
      ToPort: 25
      CidrIp: 0.0.0.0/0

  EC2AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AvailabilityZones: 
        Fn::GetAZs: ""     
      LaunchConfigurationName: !Ref Ec2Instance
      MinSize: 3
      MaxSize: 3
      DesiredCapacity: 3
      HealthCheckGracePeriod: 300
	  
  Ec2Instance:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      # KeyName: Joseph-demo
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX] #/ Amazon Linux
      SecurityGroups:
        - !Ref Ec2SecurityGroup
        - default
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      UserData:
        "Fn::Base64":
          !Sub |
          #!/bin/bash
          sudo su -
          yum install -y mailx telnet mutt dovecot amazon-efs-utils
          yum update -y
          setenforce 0
          systemctl stop firewalld
          mnt_efs=/mnt/efs
          mkdir -p $mnt_efs
          mount -t efs fs-efbb24a7:/ $mnt_efs
          useradd demo
          echo "demo:demo1" | chpasswd
          usermod -aG mail demo
          sed -i '$adisable_plaintext_auth = no' /etc/dovecot/conf.d/10-auth.conf
          # Change local storage to efs for dovecot
          sed -i "\$amail_location = mbox:~/mail:INBOX=$mnt_efs/mail/%u" /etc/dovecot/conf.d/10-mail.conf
          systemctl restart dovecot
          # Change local storage to efs for postfix
          postconf -e "mail_spool_directory = $mnt_efs/mail"
          postconf -e "inet_interfaces = all"
          postconf -e "mydestination = josephaws.one, email.josephaws.one, josephaws.com, email.josephaws.com, localhost"
          systemctl restart postfix
