Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S,M,L)

Mappings:
  RegionMap:
    us-east-1:
      "AMALINUX" : "ami-b70554c8" # AMALINUX July 2018
  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
      "DB" : "db.t2.small"
    LARGE:
      "EC2" : "t2.medium"
      "DB" : "db.t2.medium"
      
Resources:
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX] # Dynamic mapping + Pseudo Parameter
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      # KeyName: Joseph-demo
      SecurityGroups:
        - all-traffic-allowed
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd mod_ssl -y
            yum update -y
            echo "Hello World!" > /var/www/html/index.html
            wget https://github.com/chenjianAgain/gcp-dovecot-ce/raw/master/20180705/downloadpage.zip
            unzip downloadpage.zip
            cp -r downloadpage/* /var/www/html/
            systemctl start httpd
            systemctl enable httpd
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2 --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Count: "1"
        Timeout: PT15M

  myDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: josephaws.com.
      Comment: DNS name for my instance.
      Name: autodns.josephaws.com.
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt EC2.PublicIp
