Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        # Count: "1"
        Timeout: PT15M
    Properties:
      ImageId: ami-b70554c8
      KeyName: Joseph-demo
      InstanceType: t2.micro
      SecurityGroups: 
        - all-traffic-allowed
      # NetworkInterfaces: 
        # - 
          # NetworkInterfaceId: eni-b4e5cbd0
          # DeviceIndex: 0 
      Tags:
        -
          Key: Name
          Value: !Sub
            - "${StackName}-demo"
            - StackName: !Ref AWS::StackName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install -y ntp dovecot mariadb-server dovecot-mysql mailx
          systemctl restart ntpd && systemctl enable ntpd
          
          PRIVATEIP=`curl -s http://169.254.169.254/latest/meta-data/local-ipv4`
          echo "$PRIVATEIP postfix.josephaws.com" >> /etc/hosts
          hostnamectl set-hostname postfix.josephaws.com
          

          # Replace postfix config file and restart
          wget https://github.com/chenjianAgain/gcp-dovecot-ce/raw/master/MailServer/useDovecot.txt
          cat useDovecot.txt >> /etc/postfix/main.cf
          systemctl restart postfix && systemctl enable postfix
          
          # Create users
          useradd -u 2100 guest -p abc123
          useradd -u 2101 kevin -p abc123
          useradd -u 2102 eric -p abc123
          useradd -u 2103 tom -p abc123
          useradd -u 2104 jason -p abc123
          useradd -u 2105 peter -p abc123
          
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Ec2Instance --region ${AWS::Region} 

Outputs:
  URL:
    Description: Your EC2 DNS URL
    Value: !Sub 
      - '${DNSName}'
      -  DNSName: !GetAtt Ec2Instance.PublicDnsName
