Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        # Count: "1"
        Timeout: PT15M
    Properties:
      ImageId: ami-b70554c8
      KeyName: Joseph-demo
      InstanceType: t2.micro
      SecurityGroups: 
        - all-traffic-allowed
      # NetworkInterfaces: 
        # - 
          # NetworkInterfaceId: eni-b4e5cbd0
          # DeviceIndex: 0 
      Tags:
        -
          Key: Name
          Value: !Sub
            - "${StackName}-demo"
            - StackName: !Ref AWS::StackName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install -y ntp dovecot mariadb-server dovecot-mysql mailx
          systemctl restart ntpd && systemctl enable ntpd
          
          PRIVATEIP=`curl -s http://169.254.169.254/latest/meta-data/local-ipv4`
          echo "$PRIVATEIP postfix.josephaws.com" >> /etc/hosts
          hostnamectl set-hostname postfix.josephaws.com
          
          postconf -e "inet_interfaces = all"
          postconf -e 'myhostname = postfix.josephaws.com'
          postconf -e 'mydomain = josephaws.com'
          postconf -e "mydestination = josephaws.one, postfix.josephaws.one, josephaws.com, postfix.josephaws.com, localhost"
          systemctl restart postfix && systemctl enable postfix
          
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Ec2Instance --region ${AWS::Region} 

Outputs:
  URL:
    Description: Your EC2 DNS URL
    Value: !Sub 
      - '${DNSName}'
      -  DNSName: !GetAtt Ec2Instance.PublicDnsName
