Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-b70554c8
      KeyName: Joseph-demo
      SecurityGroups: 
        - all-traffic-allowed
      # NetworkInterfaces: 
        # - 
          # NetworkInterfaceId: eni-b4e5cbd0
          # DeviceIndex: 0 
      Tags:
        -
          Key: Name
          Value: Test Instance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install httpd -y
          echo hello >> /var/www/html/index.html
          systemctl restart httpd
          
          PRIVATEIP=curl http://169.254.169.254/latest/meta-data/local-ipv4
          echo "$PRIVATEIP ipa.example.com" >> /etc/hosts
Outputs:
  URL:
    Description: Your EC2 DNS URL
    Value: !Sub 
      - '${DNSName}'
      -  DNSName: !GetAtt Ec2Instance.PublicDnsName
