Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-b70554c8
      KeyName: Joseph-demo
      # NetworkInterfaces: 
        # - 
          # NetworkInterfaceId: eni-b4e5cbd0
          # DeviceIndex: 0 
      Tags:
        -
          Key: Name
          Value: Test Instance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install httpd -y
          echo hello >> /var/www/html/index.html
          systemctl restart httpd
          
          PRIVATEIP=curl http://169.254.169.254/latest/meta-data/local-ipv4
          echo $PRIVATEIP >> /etc/hosts
