Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-b70554c8
      KeyName: Joseph-demo
      NetworkInterfaces: 
        - 
          NetworkInterfaceId: eni-b4e5cbd0
          DeviceIndex: 0 
      Tags:
        -
          Key: Role
          Value: Test Instance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install ec2-net-utils -y
          ec2ifup eth1
          service httpd start
